"""
Django settings for una_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Build production-ready settings from environment variables.
# Use a safe secret key in production via .env or the environment.
SECRET_KEY = os.environ.get('871897684961814', 'django-insecure-g+w)gf-n+1$ycng2)fvgx7h4nm+%x3wg%yw@35blz-nl@iy02n')

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


JAZZMIN_SETTINGS = {
    "site_header": "UNA Admin",
    "site_brand": "Vie Estudiantine UNA",
    "welcome_sign": "Bienvenue sur le gestionnaire UNA",
    "copyright": "Université Nangui Abrogoua",
    "search_model": ["vie_estudiantine_una.Actualite"],

    # --- Bouton Voir le Site ---
    "site_url": "/",
    "topmenu_links": [
        {"name": "Voir le site", "url": "/", "new_window": True, "icon": "fas fa-globe"},
    ],
    
    # Organisation du menu latéral
    "side_menu_groups": [
        {
            "name": "Communication",
            "models": ["vie_estudiantine_una.Actualite", "vie_estudiantine_una.Evenement", "vie_estudiantine_una.Slide", "vie_estudiantine_una.Banner"],
        },
        {
            "name": "Vie Étudiante & CROU",
            "models": ["vie_estudiantine_una.OffreLogement", "vie_estudiantine_una.ServiceCROU", "vie_estudiantine_una.Club_association"],
        },
        {
            "name": "Académique & Partenaires",
            "models": ["vie_estudiantine_una.Filiere", "vie_estudiantine_una.Partenaire", "vie_estudiantine_una.Acteur"],
        },
        {
            "name": "Retours & Témoignages",
            "models": ["vie_estudiantine_una.Temoignage", "vie_estudiantine_una.Temoin"],
        },
    ],
    "icons": {
        "vie_estudiantine_una.Actualite": "fas fa-newspaper",
        "vie_estudiantine_una.Evenement": "fas fa-calendar-alt",
        "vie_estudiantine_una.OffreLogement": "fas fa-home",
        "vie_estudiantine_una.Filiere": "fas fa-graduation-cap",
    },
}


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'vie_estudiantine_una',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'una_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vie_estudiantine_una.context_processors.notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'una_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('una_site_db'),
            'USER': os.environ.get('una_site_db_user'),
            'PASSWORD': os.environ.get('stT2eZlnK9XSRUzq9ydz5WUEKAg3dKYy'),
            'HOST': os.environ.get('dpg-d7v6ne9j2pic73e6bcgg-a', 'db'),
            'PORT': os.environ.get('5432', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
   
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
STATIC_ROOT = BASE_DIR / 'staticfiles'

LOGIN_URL = 'vie_estudiantine_una:login'


EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'mrpare645@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'maroukfsvgkufbyh')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Administration UNA <mrpare645@gmail.com>')


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('daungdo60'),
    'API_KEY': os.environ.get('871897684961814'),
    'API_SECRET': os.environ.get('gwnF37Er8RIT4E0ofHeN2u4prE'),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



