# Generated by Django 6.0 on 2026-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('point_1', models.CharField(max_length=255)),
                ('point_2', models.CharField(max_length=255)),
                ('point_3', models.CharField(max_length=255)),
                ('bouton_texte', models.CharField(default='En savoir plus', max_length=100)),
                ('bouton_lien', models.URLField(default='https://www.univ-na.ci/')),
            ],
        ),
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='acteurs/')),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('UNA', 'Vie universitaire'), ('EVENT', 'Événement'), ('CROU', 'CROU'), ('CLUB', 'Club & Association')], max_length=20)),
                ('resume', models.TextField()),
                ('image', models.ImageField(upload_to='actualites/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('nom_auteur', models.CharField(default='Administration UNA', max_length=100)),
                ('image_auteur', models.ImageField(blank=True, upload_to='auteurs/')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Club_association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=100)),
                ('nom_club', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='clubs_associations/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Club/Association',
                'verbose_name_plural': 'Clubs/Associations',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('icon', models.CharField(help_text='Classe Bootstrap Icons ex: bi-mortarboard', max_length=50)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='OffreLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_logement', models.CharField(choices=[('chambre', 'Chambre'), ('studio', 'Studio'), ('appartement', 'Appartement')], max_length=50)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lieu', models.CharField(max_length=200)),
                ('contact_crou', models.CharField(max_length=200)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offre de logement',
                'verbose_name_plural': 'Offres de logement',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partenaires/')),
                ('domaine', models.CharField(max_length=100)),
                ('site_web', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
            },
        ),
        migrations.CreateModel(
            name='ServiceCROU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('logement', 'Logement'), ('restauration', 'Restauration'), ('sante', 'Santé')], max_length=50)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=200)),
                ('horaires', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=200)),
                ('lien_externe', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service CROU',
                'verbose_name_plural': 'Services CROU',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='slides/')),
                ('bouton_texte', models.CharField(blank=True, max_length=100)),
                ('bouton_lien', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant_nom', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='temoignages/')),
                ('message', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='temoins/')),
                ('message', models.TextField()),
            ],
        ),
    ]
