# Generated by Django 6.0 on 2026-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='slides/')),
                ('bouton_texte', models.CharField(blank=True, max_length=100)),
                ('bouton_lien', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['ordre'],
            },
        ),
    ]
