# Generated by Django 6.0 on 2026-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0002_add_slide_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecrou',
            name='categorie',
            field=models.CharField(choices=[('logement', 'Logement'), ('restauration', 'Restauration'), ('sante', 'Santé'), ('Autre', 'autres')], max_length=50),
        ),
    ]
