# Generated by Django 6.0 on 2026-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0003_alter_servicecrou_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about/')),
                ('actif', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bannière À propos',
                'verbose_name_plural': 'Bannières À propos',
            },
        ),
    ]
