# Generated by Django 6.0 on 2026-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0004_aboutbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('accueil', 'Accueil'), ('about', 'À propos'), ('contact', 'Contact'), ('formation', 'Formation')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutBanner',
        ),
    ]
