# Generated by Django 6.0 on 2026-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0005_banner_delete_aboutbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('about', 'À propos'), ('contact', 'Contact'), ('formation', 'Formation'), ('events', 'Événements'), ('crouA2', 'Services CROU'), ('club', 'Clubs et Associations')], max_length=50),
        ),
    ]
