# Generated by Django 6.0 on 2026-02-12 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0006_alter_banner_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temoin',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('about', 'À propos'), ('contact', 'Contact'), ('actualite', 'Actualités'), ('events', 'Événements'), ('crouA2', 'Services CROU'), ('club', 'Clubs et Associations')], max_length=50),
        ),
    ]
