# Generated by Django 6.0 on 2026-02-12 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0007_temoin_date_creation_temoin_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_association',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_association',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
