# Generated by Django 6.0 on 2026-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0008_club_association_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoin',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approuvé'),
        ),
    ]
