# Generated by Django 6.0 on 2026-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0009_alter_temoin_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoin',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
