# Generated by Django 6.0 on 2026-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0010_alter_temoin_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffreLogement',
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
        migrations.AddField(
            model_name='evenement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
