# Generated by Django 6.0 on 2026-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0011_delete_offrelogement_delete_temoignage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecrou',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
