# Generated by Django 6.0 on 2026-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0012_servicecrou_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecrou',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Service Étudiant'),
        ),
    ]
