# Generated by Django 6.0 on 2026-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0013_servicecrou_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etudiants', models.CharField(default='15000', help_text='Ex: 15000', max_length=50)),
                ('nombre_enseignants', models.CharField(default='500', help_text='Ex: 500', max_length=50)),
            ],
            options={
                'verbose_name': 'Chiffres Clés (Statistiques)',
                'verbose_name_plural': 'Chiffres Clés (Statistiques)',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('about', 'À propos'), ('contact', 'Contact'), ('actualites', 'Actualités'), ('events', 'Événements'), ('crouA2', 'Services CROU'), ('club', 'Clubs et Associations')], max_length=50),
        ),
    ]
