# Generated by Django 6.0 on 2026-02-19 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0014_statistique_alter_banner_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profils/default.jpg', upload_to='profils/')),
                ('niveau', models.CharField(blank=True, help_text='Ex: Licence 3, Master 1', max_length=50)),
                ('centres_interet', models.TextField(blank=True, help_text='Séparés par des virgules')),
                ('clubs_suivis', models.ManyToManyField(blank=True, related_name='followers', to='vie_estudiantine_una.club_association')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vie_estudiantine_una.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
            },
        ),
    ]
