# Generated by Django 6.0 on 2026-02-20 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0015_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club_association',
            name='proposer_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_proposes', to=settings.AUTH_USER_MODEL, verbose_name='Proposé par'),
        ),
        migrations.AddField(
            model_name='servicecrou',
            name='proposer_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_proposes', to=settings.AUTH_USER_MODEL, verbose_name='Proposé par'),
        ),
        migrations.AddField(
            model_name='temoin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
    ]
