# Generated by Django 6.0 on 2026-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0018_profile_bio_post_notification_postcomment_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_association',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('PENDING', 'En attente de validation'), ('REJECTED', 'Masqué / Rejeté')], default='PENDING', max_length=20, verbose_name='Statut Modération'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('PENDING', 'En attente de validation'), ('REJECTED', 'Masqué / Rejeté')], default='APPROVED', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('PENDING', 'En attente de validation'), ('REJECTED', 'Masqué / Rejeté')], default='APPROVED', max_length=20),
        ),
    ]
