# Generated by Django 6.0 on 2026-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0019_club_association_status_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('PENDING', 'En attente de validation'), ('REJECTED', 'Masqué / Rejeté')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
