# Generated by Django 6.0 on 2026-02-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vie_estudiantine_una', '0021_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vie_estudiantine_una.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('like', 'Nouveau like'), ('comment', 'Nouveau commentaire'), ('message', 'Nouveau message')], max_length=20),
        ),
    ]
